# Generated by Django 4.0 on 2021-12-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
