# Generated by Django 4.0 on 2021-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_meal_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
